# Generated by Django 2.2.4 on 2019-09-22 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_risk_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
                ('department_email', models.CharField(max_length=100)),
                ('department_number', models.CharField(max_length=30)),
                ('department_location', models.TextField()),
                ('department_costCode', models.CharField(max_length=30)),
                ('department_risk_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('asset_id', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(default='', help_text='Enter Serial Number', max_length=25)),
                ('purchase_order', models.CharField(default='', max_length=25)),
                ('cost', models.IntegerField(default=0, verbose_name='Cost in GBP')),
                ('accepted_date', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Accepted On')),
                ('warranty_expiry', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Warranty Expiry')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mems.Category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mems.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('manufacturer_email', models.CharField(max_length=100, null=True)),
                ('manufacturer_number', models.CharField(max_length=50, null=True)),
                ('manufacturer_address', models.TextField(default='', null=True)),
            ],
            options={
                'ordering': ['manufacturer_name'],
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.CharField(max_length=20)),
                ('stock_description', models.CharField(max_length=50)),
                ('stock_price', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_number', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('', ''), ('Acceptance', 'Acceptence'), ('Acceptance (Loan)', 'Acceptence Loan'), ('PPM', 'PPM'), ('Repair', 'Repair'), ('Incident', 'Incident'), ('Supply', 'Supply')], max_length=20)),
                ('job_status', models.CharField(choices=[('Created', 'Created'), ('In progress', 'In progress'), ('Completed (Acceptance)', 'Completed Acceptance'), ('Completed (Service)', 'Completed Service'), ('Completed (Repair)', 'Completed Repair'), ('Completed (Repair & Service)', 'Completed Repair and Service')], max_length=30)),
                ('job_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('job_description', models.CharField(default='', max_length=100)),
                ('job_work_done', models.TextField(blank=True, default='', max_length=300)),
                ('job_time_taken', models.IntegerField(choices=[(15, '15'), (30, '30'), (45, '45'), (60, '60'), (90, '90'), (120, '120'), (180, '180'), (240, '240')], default=0)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mems.Equipment')),
                ('job_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mems.Department')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mems.Manufacturer'),
        ),
    ]
