# Generated by Django 2.2.4 on 2019-08-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('assetId', models.AutoField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
    ]
