# Generated by Django 2.2.4 on 2019-08-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(default='aaa', max_length=15),
        ),
        migrations.AddField(
            model_name='equipment',
            name='department',
            field=models.CharField(default='aaa1', max_length=15),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(default='aaa', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serialNumber',
            field=models.CharField(default='aaa', max_length=20),
        ),
    ]
